# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cassini-hackathons-bot-container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://cassini.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_29bc70807de64e48a9277f7695f2093b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_27ca5ed4c0e745a88a82ad4e52fd2ee1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: cassini.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_29bc70807de64e48a9277f7695f2093b }}/cassini-hackathons-bot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cassini-hackathons-bot-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b9d44f8f93bc4d08a157198535f9a7c5 }}
        images: 'cassini.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_29bc70807de64e48a9277f7695f2093b }}/cassini-hackathons-bot:${{ github.sha }}'