# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container to Azure App Service (Production)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github repository'
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: https://cassinidocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e4f2eb3e680d45139d3ad0e24e579cc8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9b69a6d1215749f181240c90f451feec }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: cassinidocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e4f2eb3e680d45139d3ad0e24e579cc8 }}/cassini-hackathons-bot:${{ github.sha }}
        file: ./dockerfile

    - name: Deploy web app container using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: cassini-hackathons-bot-container
        slot-name: production
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_68a71d1d5c3c4139affe54b708be58d5 }}
        images: 'cassinidocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e4f2eb3e680d45139d3ad0e24e579cc8 }}/cassini-hackathons-bot:${{ github.sha }}'
